# Generated by Django 4.2.27 on 2026-01-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_count', models.IntegerField(default=0, help_text='Number of products successfully processed')),
                ('error_count', models.IntegerField(default=0, help_text='Number of rows with errors')),
                ('errors_log', models.TextField(blank=True, help_text='Log of errors encountered during processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uploads', to='core.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uploads', to='core.profile')),
            ],
            options={
                'verbose_name': 'Product Upload',
                'verbose_name_plural': 'Product Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_orders_enabled', models.BooleanField(default=True, help_text='Allow bulk order creation')),
                ('exports_enabled', models.BooleanField(default=True, help_text='Allow order exports')),
                ('api_access_enabled', models.BooleanField(default=True, help_text='Allow API access')),
                ('csv_upload_enabled', models.BooleanField(default=True, help_text='Allow CSV product uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggle', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Feature Toggle',
                'verbose_name_plural': 'Company Feature Toggles',
            },
        ),
    ]
